### ISSUE TITLE
x509: certificate signed by unknown authority but certificate added to ca-certificate

### ISSUE THREAD

**Issue by Acronys1** [ctrox/csi-s3#17]
Hello,

After creating PVC I have an SSL issue on csi-provisioner pod. I contact a https endpoint ( compatible storage not AWS ) so I modify the pod with postStart task to add the CA.

With exec in container I add curl and try to resolve url, it's ok and I have certificates in ca-certificate :

> curl -v https://backup.s3.xxx.xxx
> 
> * Uses proxy env variable no_proxy == '10.96.0.1'
> *   Trying 192.168.2.1...
> * TCP_NODELAY set
> * Connected to 192.168.2.1 (192.168.2.1) port 3128 (#0)
> * allocate connect buffer!
> * Establish HTTP proxy tunnel to backup.s3.xxx.xxx:443
> > CONNECT backup.s3.xxx.xxx:443 HTTP/1.1
> > Host: backup.s3.xxx.xxx:443
> > User-Agent: curl/7.64.1
> > Proxy-Connection: Keep-Alive
> > 
> < HTTP/1.1 200 Connection established
> < 
> * Proxy replied 200 to CONNECT request
> * CONNECT phase completed!
> * ALPN, offering h2
> * ALPN, offering http/1.1
> * successfully set certificate verify locations:
> *   CAfile: /etc/ssl/certs/ca-certificates.crt
>   CApath: none
> * TLSv1.3 (OUT), TLS handshake, Client hello (1):
> * CONNECT phase completed!
> * CONNECT phase completed!
> * TLSv1.3 (IN), TLS handshake, Server hello (2):
> * TLSv1.2 (IN), TLS handshake, Certificate (11):
> * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
> * TLSv1.2 (IN), TLS handshake, Server finished (14):
> * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
> * TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
> * TLSv1.2 (OUT), TLS handshake, Finished (20):
> * TLSv1.2 (IN), TLS handshake, Finished (20):
> * SSL connection using TLSv1.2 / DHE-RSA-AES256-GCM-SHA384
> * ALPN, server did not agree to a protocol
> * Server certificate:
> *  subject: C=FR; O=xxx; OU=Private Group PKI; OU=xxx; CN=backup.s3.xxx.xxx
> *  start date: May 15 13:59:53 2018 GMT
> *  expire date: May 14 14:00:53 2022 GMT
> *  subjectAltName: host "backup.s3.xxx.xxx" matched cert's "backup.s3.xxx.xxx"
> *  issuer: C=FR; O=xxx; OU=Private Group PKI; OU=xxx; CN=xxx
> *  SSL certificate verify ok.
> > GET / HTTP/1.1
> > Host: backup.s3.xxx.xxx
> > User-Agent: curl/7.64.1
> > Accept: */*
> > 
> < HTTP/1.1 403 Forbidden
> < server: S3 Server
> < x-amz-id-2: 150479598f4097ae9038
> < x-amz-request-id: 150479598f4097ae9038
> < Content-Type: application/xml
> < Content-Length: 174
> < Date: Tue, 14 May 2019 15:45:12 GMT
> < Connection: keep-alive
> < 
> * Connection #0 to host 192.168.2.1 left intact
> <?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Access Denied</Message><Resource></Resource><RequestId>150479598f4097ae9038</RequestId></Error>* Closing connection 0
> 

But I have always the ssl issue :

`I0514 15:37:23.228685       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"csi-s3-pvc", UID:"ea071c6f-765d-11e9-bf08-024fe762fd88", APIVersion:"v1", ResourceVersion:"754640", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "csi-s3": rpc error: code = Unknown desc = failed to check if bucket pvc-ea071c6f-765d-11e9-bf08-024fe762fd88 exists: Get https://backup.s3.xxx.xxx/pvc-ea071c6f-765d-11e9-bf08-024fe762fd88/?location=: x509: certificate signed by unknown authority`

Do you have an idea ?

Thanks,

Maxime

**Comment by ctrox** [comment]
Is this a self-signed certificate? If so you would need to get that CA file into the the csi-s3 docker image. You could just build a new image using `FROM ctrox/csi-s3:<version>` and then adding your CA file to the correct path.

**Comment by Acronys1** [comment]
Well, it's work. Thank you.

**Comment by Sinamcp** [comment]
Hi @mdecalf , where did you put the ca bundle?

**Comment by aneurinprice** [comment]
@Sinamcp you'll almost certainly need it in /etc/ca-certificates
