### ISSUE TITLE
Update s3fs to resolve >20 MB bug

### ISSUE THREAD

**Issue by piwi91** [ctrox/csi-s3#28]
In the current csi-s3 docker container the s3fs plugin should be updated to the latest version because it is not possible to upload files greater than 20 MB.

See https://github.com/s3fs-fuse/s3fs-fuse/issues/125 for the details.

**Comment by ctrox** [comment]
This should be resolved with the latest v1.2.0-rc.1, s3fs is now on `1.84`. It is still quite an old version since I'm just using the debian docker image as a base. I want to decouple this at some point but it should do for now. Just reopen the issue if that is not the case.
