### ISSUE TITLE
Still experimental?

### ISSUE THREAD

**Issue by Divxtaman** [CTrox/csi-s3#6]
Is it ready for production use?

**Comment by CTrox** [comment]
Yes, unfortunately I have not had the time lately to continue working on this. But I have plans on updating this to the latest CSI spec and also fixing some issues that I have noticed while using it.

**Comment by Divxtaman** [comment]
:) yes I also just noticed "yes" or "no"..., sorry about that. Well, its a wonderful project ;0 I already put it on my watchlist. happy coding...
