### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by sterchelen** [ctrox/csi-s3#73]
@ctrox Could you confirm if this project is still maintained?
Thx.

**Comment by ctrox** [comment]
I'm not actively working on new features at the moment but I look at PRs and issues and try to merge important bug fixes. Not sure if that counts as maintained, but this is just a side project that somehow got quite a few users over the years. I'll try to do a bit more on this soon but I can't promise you anything :)

**Comment by sterchelen** [comment]
Thank you @ctrox for your answer 🙇🏼‍♂️! (I'll post a question/issue regarding `defunct` processes in another issue).
Closing this one.
